version: 2

project_name: gaspeek

builds:
  - binary: gp
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

# Formula is manually maintained in nmelo/homebrew-tap for pre-built binaries
# Update Formula/gp.rb after each release with new URLs and checksums from checksums.txt

checksum:
  name_template: checksums.txt

release:
  draft: false
  prerelease: auto
